---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: titleSizeRomain
flagType: number
description: 
labels:
  - label3

availableValues:
  - 14
  - 18
  - 24
  - 12

isPermanent: false
